language: node_js
node_js:
  - 0.10
  - 0.11
  - 0.12
script: "tap test/*"
notifications:
  irc:
    channels:
      - "irc.freenode.org#TotenDev"
before_install:
  git submodule init && git submodule --quiet update
