language: node_js
node_js:
  - 0.4
  - 0.6
  - 0.7
  - 0.8
script: "tap test/*"
notifications:
  irc:
    channels:
      - "irc.freenode.org#TotenDev"
before_install:
  git submodule init && git submodule --quiet update